name: Jesper Bove-Nielsen
favicon: null
layout_spectrum: 0.9820789
typography_spectrum: 0.4265233
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Seriously Digimental
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#809EC4'
    - '#4573B2'
    - '#C5C0BA'
    - '#04080D'
    - '#2D2C2A'
  brandStrength: 0.9784434
  lightness: 0.6971326
  saturation: 0.8010753
  rhythmicContrast: 0.08064516
purpose: []
