collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4265233
color:
  saturation: 0.8010753
  brandStrength: 0.9784434
  lightness: 0.6971326
  brandColors:
    - '#809EC4'
    - '#4573B2'
    - '#C5C0BA'
    - '#04080D'
    - '#2D2C2A'
  rhythmicContrast: 0.08064516
layout_spectrum: 0.9820789
name: Jesper Bove-Nielsen
