layout_spectrum: 0.02508961
typography_spectrum: 0.4265233
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.9784434
  rhythmicContrast: 1
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Jesper Bove-Nielsen
