layout_spectrum: 0.02508961
typography_spectrum: 0.4265233
color:
  saturation: 0.8010753
  lightness: 0.6971326
  brandStrength: 0.9784434
  brandColors:
    - '#BE1E2E'
    - '#6D6E72'
    - '#FFCB08'
    - '#F1592A'
    - '#0B9444'
  rhythmicContrast: 0.05376344
name: Jesper Bove-Nielsen
